# Generated by Django 5.0.7 on 2024-08-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='slug',
            field=models.SlugField(max_length=64, unique=True),
        ),
    ]
