name: Site de Aulas

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    env:
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VIRTUALENVS: 1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -q pipenv
          pipenv sync -d

      - name: Lint with flake8
        run: |
          pipenv run flake8 .
